const Icons = {
  Burger: require("../assets/icons/Burger.png"),
  Notification: require("../assets/icons/Notification.png"),
  Search: require("../assets/icons/Search.png"),
  Education: require("../assets/icons/cil_education.png"),
  Event: require("../assets/icons/bi_calendar3-event.png"),
  Teachfess: require("../assets/icons/ph_chalkboard-teacher.png"),
  ArrowRight: require("../assets/icons/ArrowRight.png"),
  Communication: require("../assets/icons/Communication.png"),
  ArrowRoundRight: require("../assets/icons/arrowcircleright.png"),
  ArrowRightLong: require("../assets/icons/ArrowRightLong.png"),
  Group: require("../assets/icons/Group.png"),
  Chat: require("../assets/icons/Chat.png"),
  Home: require("../assets/icons/Home.png"),
  Profile: require("../assets/icons/Profile.png"),
  ChatSolid: require("../assets/icons/ChatSolid.png"),
  ProfileSolid: require("../assets/icons/ProfileSolid.png"),
  HomeSolid: require("../assets/icons/HomeSolid.png"),
};
export default Icons;
