const Icons = {
  Burger: require("../assets/icons/Burger.png"),
  Notification: require("../assets/icons/Notification.png"),
  Search: require("../assets/icons/Search.png"),
  Education: require("../assets/icons/cil_education.png"),
  Event: require("../assets/icons/bi_calendar3-event.png"),
  Teachfess: require("../assets/icons/ph_chalkboard-teacher.png"),
  ArrowRight: require("../assets/icons/ArrowRight.png"),
  Communication: require("../assets/icons/Communication.png"),
  ArrowRoundRight: require("../assets/icons/arrowcircleright.png"),
  ArrowRightLong: require("../assets/icons/ArrowRightLong.png"),
  Group: require("../assets/icons/Group.png"),
  Chat: require("../assets/icons/Chat.png"),
  Home: require("../assets/icons/Home.png"),
  Profile: require("../assets/icons/Profile.png"),
  ChatSolid: require("../assets/icons/ChatSolid.png"),
  ProfileSolid: require("../assets/icons/ProfileSolid.png"),
  HomeSolid: require("../assets/icons/HomeSolid.png"),
  Ticket: require("../assets/icons/Ticket.png"),
  Like: require("../assets/icons/Like.png"),
  Cam: require("../assets/icons/Cam.png"),
  ProfileRounded: require("../assets/icons/ProfileRounded.png"),
  AddPoto: require("../assets/icons/AddPoto.png"),
  AddImage: require("../assets/icons/AddImage.png"),
  AddEmoji: require("../assets/icons/AddEmoji.png"),
  Messages: require("../assets/icons/Messages.png"),
  Messages2: require("../assets/icons/Messages2.png"),
  Heart: require("../assets/icons/Heart.png"),
  Share: require("../assets/icons/Share.png"),
  More: require("../assets/icons/More.png"),
  Share3: require("../assets/icons/Share3.png"),
  BEM: require("../assets/icons/BEM.png"),
  Calendar: require("../assets/icons/Calendar.png"),
  Profile_2user: require("../assets/icons/Profile_2user.png"),
  Archive_tick: require("../assets/icons/Archive_tick.png"),
  Heart_half: require("../assets/icons/Heart_half.png"),
};
export default Icons;
